name: Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-alpha*'
      - 'v*.*.*-beta*'
      - 'v*.*.*-rc*'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Install fyne
      run: go install fyne.io/fyne/v2/cmd/fyne@latest

    - name: Build for macOS amd64
      run: fyne package -os darwin -arch amd64 -icon Icon.png -name owlcms

    - name: Build for macOS arm64
      run: fyne package -os darwin -arch arm64 -icon Icon.png -name owlcms

    - name: Zip macOS amd64 app
      run: |
        cd fyne-cross/dist/darwin-amd64
        zip -r owlcms-launcher_${GITHUB_REF#refs/tags/}_mac_amd64.zip owlcms-launcher.app
        cd -

    - name: Zip macOS arm64 app
      run: |
        cd fyne-cross/dist/darwin-arm64
        zip -r owlcms-launcher_${GITHUB_REF#refs/tags/}_mac_arm64.zip owlcms-launcher.app
        cd -

    - name: Create DMG for macOS amd64
      run: |
        mkdir -p fyne-cross/dist/darwin-amd64/dmg
        cp -R fyne-cross/dist/darwin-amd64/owlcms-launcher.app fyne-cross/dist/darwin-amd64/dmg/
        hdiutil create -volname "owlcms-launcher" -srcfolder fyne-cross/dist/darwin-amd64/dmg -ov -format UDZO fyne-cross/dist/darwin-amd64/owlcms-launcher_${GITHUB_REF#refs/tags/}_mac_amd64.dmg

    - name: Create DMG for macOS arm64
      run: |
        mkdir -p fyne-cross/dist/darwin-arm64/dmg
        cp -R fyne-cross/dist/darwin-arm64/owlcms-launcher.app fyne-cross/dist/darwin-arm64/dmg/
        hdiutil create -volname "owlcms-launcher" -srcfolder fyne-cross/dist/darwin-arm64/dmg -ov -format UDZO fyne-cross/dist/darwin-arm64/owlcms-launcher_${GITHUB_REF#refs/tags/}_mac_arm64.dmg

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: "owlcms-launcher ${{ github.ref }}"
        draft: false
        prerelease: false

    - name: Upload macOS amd64 zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: fyne-cross/dist/darwin-amd64/owlcms-launcher_${GITHUB_REF#refs/tags/}_mac_amd64.zip
        asset_name: owlcms-launcher_${GITHUB_REF#refs/tags/}_mac_amd64.zip
        asset_content_type: application/zip

    - name: Upload macOS arm64 zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: fyne-cross/dist/darwin-arm64/owlcms-launcher_${GITHUB_REF#refs/tags/}_mac_arm64.zip
        asset_name: owlcms-launcher_${GITHUB_REF#refs/tags/}_mac_arm64.zip
        asset_content_type: application/zip

    - name: Upload macOS amd64 DMG
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: fyne-cross/dist/darwin-amd64/owlcms-launcher_${GITHUB_REF#refs/tags/}_mac_amd64.dmg
        asset_name: owlcms-launcher_${GITHUB_REF#refs/tags/}_mac_amd64.dmg
        asset_content_type: application/x-apple-diskimage

    - name: Upload macOS arm64 DMG
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: fyne-cross/dist/darwin-arm64/owlcms-launcher_${GITHUB_REF#refs/tags/}_mac_arm64.dmg
        asset_name: owlcms-launcher_${GITHUB_REF#refs/tags/}_mac_arm64.dmg
        asset_content_type: application/x-apple-diskimage
